### ISSUE TITLE
set-fqdn always changes state in Debian

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/hostsfile-formula#10]
Does this happen on RedHat also?

Doing something like this instead of `unless: test ...` does the trick. I'm sure we could make it compatible with RedHat too.

```
cmd.run:
  - name: hostname {{ grains['id'] }}
  - onchanges:
    - file: /etc/hostname
```

Cheers!
